services:
  - type: web
    name: daily-close
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENABLE_SCHEDULER
        value: "1"
